NIFTY_500 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "LT.NS", "SBIN.NS", "AXISBANK.NS",
    "KOTAKBANK.NS", "ITC.NS", "BHARTIARTL.NS", "ASIANPAINT.NS", "HINDUNILVR.NS", "BAJFINANCE.NS", "HCLTECH.NS",
    "SUNPHARMA.NS", "WIPRO.NS", "MARUTI.NS", "ULTRACEMCO.NS", "NTPC.NS", "TECHM.NS", "POWERGRID.NS", "TITAN.NS",
    "TATASTEEL.NS", "NESTLEIND.NS", "BAJAJFINSV.NS", "JSWSTEEL.NS", "HDFCLIFE.NS", "GRASIM.NS", "CIPLA.NS",
    "ADANIENT.NS", "ADANIPORTS.NS", "ONGC.NS", "COALINDIA.NS", "SBILIFE.NS", "DRREDDY.NS", "BPCL.NS",
    "BRITANNIA.NS", "DIVISLAB.NS", "HINDALCO.NS", "EICHERMOT.NS", "SHREECEM.NS", "IOC.NS", "BAJAJ-AUTO.NS",
    "ICICIPRULI.NS", "M&M.NS", "HEROMOTOCO.NS", "INDUSINDBK.NS", "VEDL.NS", "GAIL.NS", "DLF.NS", "PIDILITIND.NS",
    "HAVELLS.NS", "AMBUJACEM.NS", "TATAMOTORS.NS", "BEL.NS", "BANKBARODA.NS", "COLPAL.NS", "PEL.NS", "PNB.NS",
    "INDIGO.NS", "ZOMATO.NS", "DMART.NS", "NAUKRI.NS", "ABB.NS", "SRF.NS", "TVSMOTOR.NS", "PAGEIND.NS",
    "BOSCHLTD.NS", "LUPIN.NS", "TRENT.NS", "GODREJCP.NS", "ICICIGI.NS", "TORNTPHARM.NS", "INDUSTOWER.NS",
    "MPHASIS.NS", "VOLTAS.NS", "BIOCON.NS", "CHOLAFIN.NS", "AUROPHARMA.NS", "BANDHANBNK.NS", "CANBK.NS",
    "MUTHOOTFIN.NS", "RECLTD.NS", "APOLLOHOSP.NS", "IRCTC.NS", "MFSL.NS", "CONCOR.NS", "L&TFH.NS", "BALKRISIND.NS",
    "ALKEM.NS", "AUBANK.NS", "IDFCFIRSTB.NS", "ESCORTS.NS", "COROMANDEL.NS", "SUNTV.NS", "IEX.NS", "FORTIS.NS",
    "HINDPETRO.NS", "JUBLFOOD.NS", "GLAND.NS", "ASHOKLEY.NS", "UBL.NS", "SYRMA.NS"
]
